@apibaseUrl = http://localhost:5000/api

### 

# Test the server
GET {{apibaseUrl}}/test

###

# Test Shorten URL
GET {{apibaseUrl}}/shorten?url=home.com

###

# Test Get Original URL
GET {{apibaseUrl}}/getOriginal?shortUrl=shortenedurl.short/6089ea00-9a47-11ed-8af1-470e8ffff95b
 